name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x, 13.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      # TODO: Add codecov as a dev dependency and run with npx

      - run: npm install
      - run: npm i -g codecov
      - run: npx nyc mocha
      - run: npx nyc report --reporter=lcov
      - run: cat ./coverage/lcov.info > coverage.lcov
      - run: npx codecov

    #   - run: npm install
    #   - run: npm run build --if-present
    #   - run: npm test
    #     env:
    #       CI: true
